# Site settings
title: BC Developers' Exchange
email: BCDevelopersExchange@gov.bc.ca
description: > # this means to ignore newlines until "baseurl:"
  The [BCDevExchange website](http://bcdevexchange.org/) is the public facing site for the BC Developers' Exchange - an experiment in tech innovation and collaboration.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bcdevexchange.org" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

exclude:
  [ Dockerfile, README.md ]

# default DevEx configuration values - can be overidden using --config flag to jekyll
#todo cleanup/delete  unused items below
apiUrl                        : "http://api.bcdevexchange.org/"
rapidAdoptionUrl              : "https://github.com/BCDevExchange/rapid-adoption-2/wiki"
# this MUST have a trailing / to work correctly
codeWithUsIssuesURL           : "http://apps-bcdevexchange-dev.pathfinder.gov.bc.ca/#/app/developers/"
programsURL                   : "https://www.bcdevexchange.org/programs"
contactUsEmail                : "BCDevelopersExchange@gov.bc.ca"
discoveryBanner               : false # whether to show experimental banner todo - grab this from old site
developersCarouselImage       : "developers.jpg"
developersImageLicenseHtml    : "Developers photo adapted from image by <a href='http://hackny.org/' analytics-on>hackny.org</a> Used under license (<a href='https://creativecommons.org/licenses/by-sa/2.0/' analytics-on>CC BY-SA 2.0</a>)"
entrepreneursCarouselImage    : "entrepreneurs.jpg"
entrepreneursImageLicenseHtml : "Entrepreneur photo adapted from The DEMO Conference by <a href='https://www.flickr.com/photos/democonference/17237592182/in/datetaken/' analytics-on>DEMO-Rentalroost-3673</a>. Used under license (<a href='https://creativecommons.org/licenses/by-nc-nd/2.0/' analytics-on>CC BY-NC-ND 2.0</a>)"
publicSectorCarouselImage     : "public-sector.jpg"
headerImageLicenseHtml        : "Cityscape photo adapted from Foggy Vancouver from West Vancouver by <a href='https://www.flickr.com/photos/gotovan/' analytics-on>GoToVan</a>. Used under license (<a href='https://creativecommons.org/licenses/by/2.0/' analytics-on>CC BY 2.0</a>)"


page_gen:
  - data: 'programdata'
    template: 'view-program'
    name: 'programname'
    dir: 'programpages'











