# Site settings
title: BC Developers' Exchange
email: BCDevelopersExchange@gov.bc.ca
description: > # this means to ignore newlines until "baseurl:"
  The [BCDevExchange website](http://bcdevexchange.org/) is the public facing site for the BC Developers' Exchange - an experiment in tech innovation and collaboration.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bcdevexchange.org" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

exclude:
  [ Dockerfile, README.md ]
